### ISSUE TITLE
Selections bar position 

### ISSUE THREAD

**Issue by modaloda** [fkabinoff/qs-dev-hub-dashboard-template#6]
when I try to checked the show selections bar in mashup editor the selections bar disappear but when check to display again it take top position of the page [https://1drv.ms/i/s!AlTV2iLjub0agtZO7bGgOuumwaDdwg](https://1drv.ms/i/s!AlTV2iLjub0agtZO7bGgOuumwaDdwg)

**Comment by modaloda** [comment]
I fond that mentioned in your documentation :)

Don't click on show selections bar or the selections toolbar will be misplaced.

**Comment by fkabinoff** [comment]
Yea. Might get around to trying to fix this at some point so that clicking show selections bar doesn't break it, but currently it does, so just avoid clicking it.
