### ISSUE TITLE
Card not auto height 

### ISSUE THREAD

**Issue by modaloda** [fkabinoff/qs-dev-hub-dashboard-template#7]
if you select chart but its height is larger than the card the chart covered the card title as this link : [https://1drv.ms/i/s!AlTV2iLjub0agtZPwjJhE0jvtZxsDw](https://1drv.ms/i/s!AlTV2iLjub0agtZPwjJhE0jvtZxsDw)

**Comment by fkabinoff** [comment]
you have to set the content-height attribute on the qliksense-card element.
