### ISSUE TITLE
Fields in filter popout do not expand

### ISSUE THREAD

**Issue by mountaindude** [fkabinoff/qs-dev-hub-dashboard-template#8]
In the underlying app I have a filter pane with a handful of fields in it. 
Dropping the filter pane into the mashup's filter popout works fine, but when I then try to expand the minimised filter, nothing happens. Which makes it Impossible to use the filter popout.
See image below.
Using Sense Sept2017.

![mashup1](https://user-images.githubusercontent.com/1029262/30991078-d9cb5d76-a4a3-11e7-9573-94c3f11cd946.jpg)

A possible workaround would be to hard code the number of filters that are needed in the filter popout... Not a very elegant solution though - but I think it should work.

**Comment by mountaindude** [comment]
Hmm, can't get that workaround to work... any ideas on how to add multiple, individual fields to the filter popout?

**Comment by fosuzuki** [comment]
Hi @mountaindude, same issue here. Did you find a solution for this?
